Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0453ec754f44f9a4a
      InstanceType: t2.micro
      Tags:
        - Key: stage
          Value: production
